int8 NONE = 0

---

int32[] in_cars
int32[] out_cars

bool[] in_fake
bool[] out_fake

# int32[] entered_cars

# int32[] exited_cars
# float32[] exited_cars_time

# bool[] is_illegal_entered_cars
# bool[] is_illegal_exited_cars

# ---
# bool does_work_out
